part of 'talk_manager_bloc.dart';

@immutable
abstract class TalkManagerEvent {}

class LoadChats extends TalkManagerEvent {}

class _UpdateChats extends TalkManagerEvent {
  final List<ExtendedChat> chatList;

  _UpdateChats(this.chatList);
}

class AutoOpenChat extends TalkManagerEvent {}

class AddChat extends TalkManagerEvent {
  final String? chatName;
  final bool isAutoGenerated;

  AddChat({this.chatName, this.isAutoGenerated = false});
}

class ModifyChats extends TalkManagerEvent {
  final List<int> chatIds;

  ModifyChats(this.chatIds);
}
