name: ai_assist
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.2
  logger: ^1.2.2
  rxdart: ^0.27.7
  google_fonts: ^4.0.5
  flutter_syntax_view: ^4.0.0
  shared_preferences: ^2.1.1
  timeago: ^3.4.0
  gpt_api:
    git:
      url: https://github.com/animousen4/gpt_api.git
      ref: master
  build_runner: ^2.3.3
  drift: ^2.5.0
  path_provider: ^2.0.13
  chat_bubbles: ^1.4.1
  auto_route_generator: ^5.0.3
  sqflite: ^2.2.6
  sqlite3_flutter_libs: ^0.5.13
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.5.2
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.2


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
